@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.frostfire.summoner.crafting;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;